---
- hosts: bench
  become: yes
  gather_facts: no
  tasks:
    - name: mkdir /usr/local/go
      file: path=/usr/local/go state=directory
    - name: check arch
      command: dpkg --print-architecture
      register: arch_res
      check_mode: no
    - name: download go binary
      unarchive:
        src="https://golang.org/dl/go1.17.7.linux-{{ arch_res.stdout }}.tar.gz"
        dest=/usr/local/
        remote_src=yes
