---
- hosts: bench
  become: yes
  become_user: isucon
  gather_facts: no
  tasks:
    - git:
        repo=https://github.com/tagomoris/xbuild.git
        dest=/home/isucon/.xbuild
        update=yes
    - command: /home/isucon/.xbuild/go-install 1.16.4 /home/isucon/.local/go
      args:
        creates: /home/isucon/.local/go/bin/go

