---
- hosts: guests:extras
  become: yes
  gather_facts: no
  tasks:
    - apt: name=nginx
    - name: clean nginx
      file: path=/etc/nginx/sites-available/default state=absent
    - name: clean nginx
      file: path=/etc/nginx/sites-enabled/default state=absent
    - copy: src=../files/etc/nginx/sites-available/isucon.conf dest=/etc/nginx/sites-available/isucon.conf owner=root mode=644
    - file: src=/etc/nginx/sites-available/isucon.conf dest=/etc/nginx/sites-enabled/isucon.conf state=link
