#!/bin/bash

mysql_container=$(docker ps | grep $(docker compose ps | grep mysql | cut -f 1 -d ' ') | cut -f 1 -d ' ')

TMP_SLOW_QUERY_LOG=/var/log/mysql/slow_query_$(date +%Y%m%d%H%M).digest
echo "Write latest sloq_query_log to ${TMP_SLOW_QUERY_LOG} from now until press Ctrl-C"
docker exec -it $mysql_container mysql -u root -proot -e 'SET GLOBAL slow_query_log_file = "'${TMP_SLOW_QUERY_LOG}'"'
# trap "docker exec -it $mysql_container mysql -u root -proot -e 'SET GLOBAL slow_query_log_file = "/var/log/mysql/mysql-slow.log"'" 2
make benchmarker
docker exec -it $mysql_container mysql -u root -proot -e 'SET GLOBAL slow_query_log_file = "/var/log/mysql/mysql-slow.log"'
# read -r -d '' _ </dev/tty
